//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryManagementSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryManagementSystem.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie den Gebührensatz an..
        /// </summary>
        internal static string ChargeRateValue {
            get {
                return ResourceManager.GetString("ChargeRateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEHLER: Die Laderate ist höher als die Höchstgrenze..
        /// </summary>
        internal static string HIGH_CHARGERATE_BREACH {
            get {
                return ResourceManager.GetString("HIGH_CHARGERATE_BREACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNUNG: Die Laderate erreicht bald die maximale Grenze..
        /// </summary>
        internal static string HIGH_CHARGERATE_WARNING {
            get {
                return ResourceManager.GetString("HIGH_CHARGERATE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEHLER: Der Ladezustand ist höher als die Höchstgrenze..
        /// </summary>
        internal static string HIGH_SOC_BREACH {
            get {
                return ResourceManager.GetString("HIGH_SOC_BREACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNUNG: Der Ladezustand steht kurz vor dem Erreichen der Höchstgrenze..
        /// </summary>
        internal static string HIGH_SOC_WARNING {
            get {
                return ResourceManager.GetString("HIGH_SOC_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEHLER: Die Temperatur ist höher als die Höchstgrenze..
        /// </summary>
        internal static string HighTempBreach {
            get {
                return ResourceManager.GetString("HighTempBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNUNG: Die Temperatur ist kurz vor dem Erreichen der Höchstgrenze..
        /// </summary>
        internal static string HighTempWarning {
            get {
                return ResourceManager.GetString("HighTempWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie eine gültige Eingabe ein.
        /// </summary>
        internal static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEHLER: Der Ladezustand liegt unter der Mindestgrenze..
        /// </summary>
        internal static string LOW_SOC_BREACH {
            get {
                return ResourceManager.GetString("LOW_SOC_BREACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNUNG: Der Ladezustand erreicht ungefähr die Mindestgrenze..
        /// </summary>
        internal static string LOW_SOC_WARNING {
            get {
                return ResourceManager.GetString("LOW_SOC_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEHLER: Die Temperatur ist niedriger als die Mindestgrenze..
        /// </summary>
        internal static string LowTempBreach {
            get {
                return ResourceManager.GetString("LowTempBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNUNG: Die Temperatur erreicht ungefähr die Mindestgrenze..
        /// </summary>
        internal static string LowTempWarning {
            get {
                return ResourceManager.GetString("LowTempWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung: Annäherung an die Entladung.
        /// </summary>
        internal static string LowWarningMessage {
            get {
                return ResourceManager.GetString("LowWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Laderate ist normal..
        /// </summary>
        internal static string NORMAL_CHARGERATE {
            get {
                return ResourceManager.GetString("NORMAL_CHARGERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Ladezustand liegt im normalen Bereich.
        /// </summary>
        internal static string NORMAL_SOC {
            get {
                return ResourceManager.GetString("NORMAL_SOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Temperatur ist im normalen Grenzbereich..
        /// </summary>
        internal static string NormalTemp {
            get {
                return ResourceManager.GetString("NormalTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung: Annäherung an die Ladungsspitze.
        /// </summary>
        internal static string PeakWarningMessage {
            get {
                return ResourceManager.GetString("PeakWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie den Ladezustand an..
        /// </summary>
        internal static string SocValue {
            get {
                return ResourceManager.GetString("SocValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie die Temperatureinheit an.
        /// </summary>
        internal static string TemperatureUnitInput {
            get {
                return ResourceManager.GetString("TemperatureUnitInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Celsius.
        /// </summary>
        internal static string TemperatureUnitInput1 {
            get {
                return ResourceManager.GetString("TemperatureUnitInput1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Fahrenheit.
        /// </summary>
        internal static string TemperatureUnitInput2 {
            get {
                return ResourceManager.GetString("TemperatureUnitInput2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie den Temperaturwert an.
        /// </summary>
        internal static string TemperatureValue {
            get {
                return ResourceManager.GetString("TemperatureValue", resourceCulture);
            }
        }
    }
}
