//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryManagementSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatteryManagementSystem.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Charge rate value..
        /// </summary>
        internal static string ChargeRateValue {
            get {
                return ResourceManager.GetString("ChargeRateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Charge rate is higher than the maximum limit..
        /// </summary>
        internal static string HIGH_CHARGERATE_BREACH {
            get {
                return ResourceManager.GetString("HIGH_CHARGERATE_BREACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING:Charge rate is about to reach maximum limit..
        /// </summary>
        internal static string HIGH_CHARGERATE_WARNING {
            get {
                return ResourceManager.GetString("HIGH_CHARGERATE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:State of charge is higher than the maximum limit..
        /// </summary>
        internal static string HIGH_SOC_BREACH {
            get {
                return ResourceManager.GetString("HIGH_SOC_BREACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING:State of charge is about to reach maximum limit..
        /// </summary>
        internal static string HIGH_SOC_WARNING {
            get {
                return ResourceManager.GetString("HIGH_SOC_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Temperature is higher than the maximum limit..
        /// </summary>
        internal static string HighTempBreach {
            get {
                return ResourceManager.GetString("HighTempBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING:Temperature is about to reach maximum limit..
        /// </summary>
        internal static string HighTempWarning {
            get {
                return ResourceManager.GetString("HighTempWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid input.
        /// </summary>
        internal static string InvalidInputMessage {
            get {
                return ResourceManager.GetString("InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:State of charge is lower than minimum limit..
        /// </summary>
        internal static string LOW_SOC_BREACH {
            get {
                return ResourceManager.GetString("LOW_SOC_BREACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING:State of charge is about reach minimum limit..
        /// </summary>
        internal static string LOW_SOC_WARNING {
            get {
                return ResourceManager.GetString("LOW_SOC_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:Temperature is lower than minimum limit..
        /// </summary>
        internal static string LowTempBreach {
            get {
                return ResourceManager.GetString("LowTempBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING:Temperature is about reach minimum limit..
        /// </summary>
        internal static string LowTempWarning {
            get {
                return ResourceManager.GetString("LowTempWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Approaching discharge.
        /// </summary>
        internal static string LowWarningMessage {
            get {
                return ResourceManager.GetString("LowWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge rate is in normal limit..
        /// </summary>
        internal static string NORMAL_CHARGERATE {
            get {
                return ResourceManager.GetString("NORMAL_CHARGERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State of charge is in normal range.
        /// </summary>
        internal static string NORMAL_SOC {
            get {
                return ResourceManager.GetString("NORMAL_SOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature is in normal limit..
        /// </summary>
        internal static string NormalTemp {
            get {
                return ResourceManager.GetString("NormalTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Approaching charge-peak.
        /// </summary>
        internal static string PeakWarningMessage {
            get {
                return ResourceManager.GetString("PeakWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide state of charge value..
        /// </summary>
        internal static string SocValue {
            get {
                return ResourceManager.GetString("SocValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the temperature unit.
        /// </summary>
        internal static string TemperatureUnitInput {
            get {
                return ResourceManager.GetString("TemperatureUnitInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Celsius.
        /// </summary>
        internal static string TemperatureUnitInput1 {
            get {
                return ResourceManager.GetString("TemperatureUnitInput1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Fahrenheit.
        /// </summary>
        internal static string TemperatureUnitInput2 {
            get {
                return ResourceManager.GetString("TemperatureUnitInput2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide temperature value.
        /// </summary>
        internal static string TemperatureValue {
            get {
                return ResourceManager.GetString("TemperatureValue", resourceCulture);
            }
        }
    }
}
